"""0003 renombra las 54 tablas a español (plural).

Revisión ID: 0003
Depende de: 5071c4b02dbd (0002)

PostgreSQL conserva datos, claves foráneas e índices al hacer RENAME;
solo se actualizan los nombres de índices y constraints únicos para que
coincidan con los modelos (evita churn en futuros autogenerate).
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '0003'
down_revision: Union[str, None] = '5071c4b02dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Si el esquema ya está en español (creado por 0001 con los modelos
    # actuales), no hay nada que renombrar.
    inspector = sa.inspect(op.get_bind())
    if inspector.has_table('eventos_app') and not inspector.has_table('app_events'):
        return
    op.rename_table('app_events', 'eventos_app')
    op.rename_table('audit_logs', 'registros_auditoria')
    op.rename_table('automation_rules', 'reglas_automatizacion')
    op.rename_table('bayes_analyses', 'analisis_bayes')
    op.rename_table('branches', 'sucursales')
    op.rename_table('categories', 'categorias')
    op.rename_table('companies', 'empresas')
    op.rename_table('customer_interactions', 'interacciones_clientes')
    op.rename_table('customer_segments', 'segmentos_clientes')
    op.rename_table('customers', 'clientes')
    op.rename_table('data_exports', 'exportaciones_datos')
    op.rename_table('dataset_variables', 'variables_conjunto')
    op.rename_table('datasets', 'conjuntos_datos')
    op.rename_table('employees', 'empleados')
    op.rename_table('insights', 'hallazgos')
    op.rename_table('inventory', 'inventario')
    op.rename_table('inventory_movements', 'movimientos_inventario')
    op.rename_table('kpi_snapshots', 'instantaneas_kpi')
    op.rename_table('login_attempts', 'intentos_login')
    op.rename_table('notifications', 'notificaciones')
    op.rename_table('observations', 'observaciones')
    op.rename_table('password_resets', 'recuperaciones_password')
    op.rename_table('payments', 'pagos')
    op.rename_table('permissions', 'permisos')
    op.rename_table('price_list_items', 'detalle_listas_precios')
    op.rename_table('price_lists', 'listas_precios')
    op.rename_table('product_promotions', 'productos_promociones')
    op.rename_table('products', 'productos')
    op.rename_table('promotions', 'promociones')
    op.rename_table('purchase_order_details', 'detalle_ordenes_compra')
    op.rename_table('purchase_orders', 'ordenes_compra')
    op.rename_table('quote_details', 'detalle_cotizaciones')
    op.rename_table('quotes', 'cotizaciones')
    op.rename_table('random_variables', 'variables_aleatorias')
    op.rename_table('refresh_tokens', 'tokens_refresco')
    op.rename_table('reports', 'reportes')
    op.rename_table('role_permissions', 'roles_permisos')
    op.rename_table('sale_details', 'detalle_ventas')
    op.rename_table('sales', 'ventas')
    op.rename_table('sales_return_details', 'detalle_devoluciones')
    op.rename_table('sales_returns', 'devoluciones')
    op.rename_table('scheduled_reports', 'reportes_programados')
    op.rename_table('shipments', 'envios')
    op.rename_table('statistical_analyses', 'analisis_estadisticos')
    op.rename_table('statistical_results', 'resultados_estadisticos')
    op.rename_table('stock_count_details', 'detalle_conteos')
    op.rename_table('stock_counts', 'conteos_stock')
    op.rename_table('suppliers', 'proveedores')
    op.rename_table('system_settings', 'ajustes_sistema')
    op.rename_table('units', 'unidades')
    op.rename_table('users', 'usuarios')
    op.rename_table('warehouse_stocks', 'stock_almacenes')
    op.rename_table('warehouses', 'almacenes')

    op.execute('ALTER INDEX "ix_users_email" RENAME TO "ix_usuarios_email"')
    op.execute('ALTER INDEX "ix_users_company_id" RENAME TO "ix_usuarios_company_id"')
    op.execute('ALTER INDEX "ix_employees_company_id" RENAME TO "ix_empleados_company_id"')
    op.execute('ALTER INDEX "ix_customers_company_id" RENAME TO "ix_clientes_company_id"')
    op.execute('ALTER INDEX "ix_customers_document_number" RENAME TO "ix_clientes_document_number"')
    op.execute('ALTER INDEX "ix_categories_company_id" RENAME TO "ix_categorias_company_id"')
    op.execute('ALTER INDEX "ix_products_company_id" RENAME TO "ix_productos_company_id"')
    op.execute('ALTER INDEX "ix_products_category_id" RENAME TO "ix_productos_category_id"')
    op.execute('ALTER INDEX "ix_products_sku" RENAME TO "ix_productos_sku"')
    op.execute('ALTER INDEX "ix_sales_status" RENAME TO "ix_ventas_status"')
    op.execute('ALTER INDEX "ix_sales_customer_id" RENAME TO "ix_ventas_customer_id"')
    op.execute('ALTER INDEX "ix_sales_company_id" RENAME TO "ix_ventas_company_id"')
    op.execute('ALTER INDEX "ix_sales_sold_at" RENAME TO "ix_ventas_sold_at"')
    op.execute('ALTER INDEX "ix_sales_sale_number" RENAME TO "ix_ventas_sale_number"')
    op.execute('ALTER INDEX "ix_sales_seller_id" RENAME TO "ix_ventas_seller_id"')
    op.execute('ALTER INDEX "ix_sale_details_product_id" RENAME TO "ix_detalle_ventas_product_id"')
    op.execute('ALTER INDEX "ix_sale_details_sale_id" RENAME TO "ix_detalle_ventas_sale_id"')
    op.execute('ALTER INDEX "ix_payments_sale_id" RENAME TO "ix_pagos_sale_id"')
    op.execute('ALTER INDEX "ix_inventory_product_id" RENAME TO "ix_inventario_product_id"')
    op.execute('ALTER INDEX "ix_inventory_movements_product_id" RENAME TO "ix_movimientos_inventario_product_id"')
    op.execute('ALTER INDEX "ix_datasets_company_id" RENAME TO "ix_conjuntos_datos_company_id"')
    op.execute('ALTER INDEX "ix_dataset_variables_dataset_id" RENAME TO "ix_variables_conjunto_dataset_id"')
    op.execute('ALTER INDEX "ix_observations_data_gin" RENAME TO "ix_observaciones_data_gin"')
    op.execute('ALTER INDEX "ix_observations_dataset_id" RENAME TO "ix_observaciones_dataset_id"')
    op.execute('ALTER INDEX "ix_statistical_analyses_analysis_type" RENAME TO "ix_analisis_estadisticos_analysis_type"')
    op.execute('ALTER INDEX "ix_statistical_analyses_company_id" RENAME TO "ix_analisis_estadisticos_company_id"')
    op.execute('ALTER INDEX "ix_statistical_analyses_dataset_id" RENAME TO "ix_analisis_estadisticos_dataset_id"')
    op.execute('ALTER INDEX "ix_statistical_results_analysis_id" RENAME TO "ix_resultados_estadisticos_analysis_id"')
    op.execute('ALTER INDEX "ix_bayes_analyses_company_id" RENAME TO "ix_analisis_bayes_company_id"')
    op.execute('ALTER INDEX "ix_random_variables_analysis_id" RENAME TO "ix_variables_aleatorias_analysis_id"')
    op.execute('ALTER INDEX "ix_random_variables_company_id" RENAME TO "ix_variables_aleatorias_company_id"')
    op.execute('ALTER INDEX "ix_insights_analysis_id" RENAME TO "ix_hallazgos_analysis_id"')
    op.execute('ALTER INDEX "ix_insights_company_id" RENAME TO "ix_hallazgos_company_id"')
    op.execute('ALTER INDEX "ix_insights_rule_code" RENAME TO "ix_hallazgos_rule_code"')
    op.execute('ALTER INDEX "ix_insights_severity" RENAME TO "ix_hallazgos_severity"')
    op.execute('ALTER INDEX "ix_reports_company_id" RENAME TO "ix_reportes_company_id"')
    op.execute('ALTER INDEX "ix_reports_report_type" RENAME TO "ix_reportes_report_type"')
    op.execute('ALTER INDEX "ix_audit_logs_user_id" RENAME TO "ix_registros_auditoria_user_id"')
    op.execute('ALTER INDEX "ix_audit_logs_action" RENAME TO "ix_registros_auditoria_action"')
    op.execute('ALTER INDEX "ix_audit_logs_company_created" RENAME TO "ix_registros_auditoria_company_created"')
    op.execute('ALTER INDEX "ix_audit_logs_company_id" RENAME TO "ix_registros_auditoria_company_id"')
    op.execute('ALTER INDEX "ix_branches_company_id" RENAME TO "ix_sucursales_company_id"')
    op.execute('ALTER INDEX "ix_suppliers_company_id" RENAME TO "ix_proveedores_company_id"')
    op.execute('ALTER INDEX "ix_purchase_orders_company_id" RENAME TO "ix_ordenes_compra_company_id"')
    op.execute('ALTER INDEX "ix_purchase_orders_supplier_id" RENAME TO "ix_ordenes_compra_supplier_id"')
    op.execute('ALTER INDEX "ix_purchase_order_details_purchase_order_id" RENAME TO "ix_detalle_ordenes_compra_purchase_order_id"')
    op.execute('ALTER INDEX "ix_purchase_order_details_product_id" RENAME TO "ix_detalle_ordenes_compra_product_id"')
    op.execute('ALTER INDEX "ix_quotes_customer_id" RENAME TO "ix_cotizaciones_customer_id"')
    op.execute('ALTER INDEX "ix_quotes_company_id" RENAME TO "ix_cotizaciones_company_id"')
    op.execute('ALTER INDEX "ix_quote_details_product_id" RENAME TO "ix_detalle_cotizaciones_product_id"')
    op.execute('ALTER INDEX "ix_quote_details_quote_id" RENAME TO "ix_detalle_cotizaciones_quote_id"')
    op.execute('ALTER INDEX "ix_sales_returns_sale_id" RENAME TO "ix_devoluciones_sale_id"')
    op.execute('ALTER INDEX "ix_sales_returns_company_id" RENAME TO "ix_devoluciones_company_id"')
    op.execute('ALTER INDEX "ix_sales_return_details_return_id" RENAME TO "ix_detalle_devoluciones_return_id"')
    op.execute('ALTER INDEX "ix_sales_return_details_product_id" RENAME TO "ix_detalle_devoluciones_product_id"')
    op.execute('ALTER INDEX "ix_units_company_id" RENAME TO "ix_unidades_company_id"')
    op.execute('ALTER INDEX "ix_price_lists_company_id" RENAME TO "ix_listas_precios_company_id"')
    op.execute('ALTER INDEX "ix_price_list_items_price_list_id" RENAME TO "ix_detalle_listas_precios_price_list_id"')
    op.execute('ALTER INDEX "ix_price_list_items_product_id" RENAME TO "ix_detalle_listas_precios_product_id"')
    op.execute('ALTER INDEX "ix_promotions_company_id" RENAME TO "ix_promociones_company_id"')
    op.execute('ALTER INDEX "ix_product_promotions_product_id" RENAME TO "ix_productos_promociones_product_id"')
    op.execute('ALTER INDEX "ix_product_promotions_promotion_id" RENAME TO "ix_productos_promociones_promotion_id"')
    op.execute('ALTER INDEX "ix_customer_segments_company_id" RENAME TO "ix_segmentos_clientes_company_id"')
    op.execute('ALTER INDEX "ix_customer_interactions_customer_id" RENAME TO "ix_interacciones_clientes_customer_id"')
    op.execute('ALTER INDEX "ix_customer_interactions_company_id" RENAME TO "ix_interacciones_clientes_company_id"')
    op.execute('ALTER INDEX "ix_warehouses_company_id" RENAME TO "ix_almacenes_company_id"')
    op.execute('ALTER INDEX "ix_warehouse_stocks_warehouse_id" RENAME TO "ix_stock_almacenes_warehouse_id"')
    op.execute('ALTER INDEX "ix_warehouse_stocks_product_id" RENAME TO "ix_stock_almacenes_product_id"')
    op.execute('ALTER INDEX "ix_stock_counts_warehouse_id" RENAME TO "ix_conteos_stock_warehouse_id"')
    op.execute('ALTER INDEX "ix_stock_counts_company_id" RENAME TO "ix_conteos_stock_company_id"')
    op.execute('ALTER INDEX "ix_stock_count_details_stock_count_id" RENAME TO "ix_detalle_conteos_stock_count_id"')
    op.execute('ALTER INDEX "ix_stock_count_details_product_id" RENAME TO "ix_detalle_conteos_product_id"')
    op.execute('ALTER INDEX "ix_shipments_sale_id" RENAME TO "ix_envios_sale_id"')
    op.execute('ALTER INDEX "ix_shipments_company_id" RENAME TO "ix_envios_company_id"')
    op.execute('ALTER INDEX "ix_role_permissions_permission_id" RENAME TO "ix_roles_permisos_permission_id"')
    op.execute('ALTER INDEX "ix_role_permissions_role_id" RENAME TO "ix_roles_permisos_role_id"')
    op.execute('ALTER INDEX "ix_refresh_tokens_user_id" RENAME TO "ix_tokens_refresco_user_id"')
    op.execute('ALTER INDEX "ix_refresh_tokens_token_hash" RENAME TO "ix_tokens_refresco_token_hash"')
    op.execute('ALTER INDEX "ix_login_attempts_user_id" RENAME TO "ix_intentos_login_user_id"')
    op.execute('ALTER INDEX "ix_login_attempts_attempted_at" RENAME TO "ix_intentos_login_attempted_at"')
    op.execute('ALTER INDEX "ix_password_resets_token_hash" RENAME TO "ix_recuperaciones_password_token_hash"')
    op.execute('ALTER INDEX "ix_password_resets_user_id" RENAME TO "ix_recuperaciones_password_user_id"')
    op.execute('ALTER INDEX "ix_kpi_snapshots_company_id" RENAME TO "ix_instantaneas_kpi_company_id"')
    op.execute('ALTER INDEX "ix_kpi_snapshots_kpi_code" RENAME TO "ix_instantaneas_kpi_kpi_code"')
    op.execute('ALTER INDEX "ix_scheduled_reports_company_id" RENAME TO "ix_reportes_programados_company_id"')
    op.execute('ALTER INDEX "ix_data_exports_company_id" RENAME TO "ix_exportaciones_datos_company_id"')
    op.execute('ALTER INDEX "ix_automation_rules_company_id" RENAME TO "ix_reglas_automatizacion_company_id"')
    op.execute('ALTER INDEX "ix_notifications_user_id" RENAME TO "ix_notificaciones_user_id"')
    op.execute('ALTER INDEX "ix_notifications_company_id" RENAME TO "ix_notificaciones_company_id"')
    op.execute('ALTER INDEX "ix_system_settings_company_id" RENAME TO "ix_ajustes_sistema_company_id"')
    op.execute('ALTER INDEX "ix_app_events_event_type" RENAME TO "ix_eventos_app_event_type"')
    op.execute('ALTER INDEX "ix_app_events_company_id" RENAME TO "ix_eventos_app_company_id"')

    op.execute('ALTER TABLE "clientes" RENAME CONSTRAINT "uq_customers_company_document" TO "uq_clientes_company_document"')
    op.execute('ALTER TABLE "categorias" RENAME CONSTRAINT "uq_categories_company_name" TO "uq_categorias_company_name"')
    op.execute('ALTER TABLE "productos" RENAME CONSTRAINT "uq_products_company_sku" TO "uq_productos_company_sku"')
    op.execute('ALTER TABLE "variables_conjunto" RENAME CONSTRAINT "uq_dataset_variables_dataset_name" TO "uq_variables_conjunto_dataset_name"')
    op.execute('ALTER TABLE "sucursales" RENAME CONSTRAINT "uq_branches_company_code" TO "uq_sucursales_company_code"')
    op.execute('ALTER TABLE "proveedores" RENAME CONSTRAINT "uq_suppliers_company_ruc" TO "uq_proveedores_company_ruc"')
    op.execute('ALTER TABLE "ordenes_compra" RENAME CONSTRAINT "uq_purchase_orders_company_number" TO "uq_ordenes_compra_company_number"')
    op.execute('ALTER TABLE "cotizaciones" RENAME CONSTRAINT "uq_quotes_company_number" TO "uq_cotizaciones_company_number"')
    op.execute('ALTER TABLE "devoluciones" RENAME CONSTRAINT "uq_sales_returns_company_number" TO "uq_devoluciones_company_number"')
    op.execute('ALTER TABLE "unidades" RENAME CONSTRAINT "uq_units_company_name" TO "uq_unidades_company_name"')
    op.execute('ALTER TABLE "detalle_listas_precios" RENAME CONSTRAINT "uq_price_list_items_list_product" TO "uq_detalle_listas_precios_list_product"')
    op.execute('ALTER TABLE "productos_promociones" RENAME CONSTRAINT "uq_product_promotions_promo_product" TO "uq_productos_promociones_promo_product"')
    op.execute('ALTER TABLE "segmentos_clientes" RENAME CONSTRAINT "uq_customer_segments_company_name" TO "uq_segmentos_clientes_company_name"')
    op.execute('ALTER TABLE "almacenes" RENAME CONSTRAINT "uq_warehouses_company_code" TO "uq_almacenes_company_code"')
    op.execute('ALTER TABLE "stock_almacenes" RENAME CONSTRAINT "uq_warehouse_stocks_wh_product" TO "uq_stock_almacenes_wh_product"')
    op.execute('ALTER TABLE "conteos_stock" RENAME CONSTRAINT "uq_stock_counts_company_number" TO "uq_conteos_stock_company_number"')
    op.execute('ALTER TABLE "envios" RENAME CONSTRAINT "uq_shipments_company_tracking" TO "uq_envios_company_tracking"')
    op.execute('ALTER TABLE "roles_permisos" RENAME CONSTRAINT "uq_role_permissions_role_permission" TO "uq_roles_permisos_role_permission"')
    op.execute('ALTER TABLE "reglas_automatizacion" RENAME CONSTRAINT "uq_automation_rules_company_code" TO "uq_reglas_automatizacion_company_code"')
    op.execute('ALTER TABLE "ajustes_sistema" RENAME CONSTRAINT "uq_system_settings_company_key" TO "uq_ajustes_sistema_company_key"')


def downgrade() -> None:
    op.execute('ALTER TABLE "ajustes_sistema" RENAME CONSTRAINT "uq_ajustes_sistema_company_key" TO "uq_system_settings_company_key"')
    op.execute('ALTER TABLE "reglas_automatizacion" RENAME CONSTRAINT "uq_reglas_automatizacion_company_code" TO "uq_automation_rules_company_code"')
    op.execute('ALTER TABLE "roles_permisos" RENAME CONSTRAINT "uq_roles_permisos_role_permission" TO "uq_role_permissions_role_permission"')
    op.execute('ALTER TABLE "envios" RENAME CONSTRAINT "uq_envios_company_tracking" TO "uq_shipments_company_tracking"')
    op.execute('ALTER TABLE "conteos_stock" RENAME CONSTRAINT "uq_conteos_stock_company_number" TO "uq_stock_counts_company_number"')
    op.execute('ALTER TABLE "stock_almacenes" RENAME CONSTRAINT "uq_stock_almacenes_wh_product" TO "uq_warehouse_stocks_wh_product"')
    op.execute('ALTER TABLE "almacenes" RENAME CONSTRAINT "uq_almacenes_company_code" TO "uq_warehouses_company_code"')
    op.execute('ALTER TABLE "segmentos_clientes" RENAME CONSTRAINT "uq_segmentos_clientes_company_name" TO "uq_customer_segments_company_name"')
    op.execute('ALTER TABLE "productos_promociones" RENAME CONSTRAINT "uq_productos_promociones_promo_product" TO "uq_product_promotions_promo_product"')
    op.execute('ALTER TABLE "detalle_listas_precios" RENAME CONSTRAINT "uq_detalle_listas_precios_list_product" TO "uq_price_list_items_list_product"')
    op.execute('ALTER TABLE "unidades" RENAME CONSTRAINT "uq_unidades_company_name" TO "uq_units_company_name"')
    op.execute('ALTER TABLE "devoluciones" RENAME CONSTRAINT "uq_devoluciones_company_number" TO "uq_sales_returns_company_number"')
    op.execute('ALTER TABLE "cotizaciones" RENAME CONSTRAINT "uq_cotizaciones_company_number" TO "uq_quotes_company_number"')
    op.execute('ALTER TABLE "ordenes_compra" RENAME CONSTRAINT "uq_ordenes_compra_company_number" TO "uq_purchase_orders_company_number"')
    op.execute('ALTER TABLE "proveedores" RENAME CONSTRAINT "uq_proveedores_company_ruc" TO "uq_suppliers_company_ruc"')
    op.execute('ALTER TABLE "sucursales" RENAME CONSTRAINT "uq_sucursales_company_code" TO "uq_branches_company_code"')
    op.execute('ALTER TABLE "variables_conjunto" RENAME CONSTRAINT "uq_variables_conjunto_dataset_name" TO "uq_dataset_variables_dataset_name"')
    op.execute('ALTER TABLE "productos" RENAME CONSTRAINT "uq_productos_company_sku" TO "uq_products_company_sku"')
    op.execute('ALTER TABLE "categorias" RENAME CONSTRAINT "uq_categorias_company_name" TO "uq_categories_company_name"')
    op.execute('ALTER TABLE "clientes" RENAME CONSTRAINT "uq_clientes_company_document" TO "uq_customers_company_document"')

    op.execute('ALTER INDEX "ix_eventos_app_company_id" RENAME TO "ix_app_events_company_id"')
    op.execute('ALTER INDEX "ix_eventos_app_event_type" RENAME TO "ix_app_events_event_type"')
    op.execute('ALTER INDEX "ix_ajustes_sistema_company_id" RENAME TO "ix_system_settings_company_id"')
    op.execute('ALTER INDEX "ix_notificaciones_company_id" RENAME TO "ix_notifications_company_id"')
    op.execute('ALTER INDEX "ix_notificaciones_user_id" RENAME TO "ix_notifications_user_id"')
    op.execute('ALTER INDEX "ix_reglas_automatizacion_company_id" RENAME TO "ix_automation_rules_company_id"')
    op.execute('ALTER INDEX "ix_exportaciones_datos_company_id" RENAME TO "ix_data_exports_company_id"')
    op.execute('ALTER INDEX "ix_reportes_programados_company_id" RENAME TO "ix_scheduled_reports_company_id"')
    op.execute('ALTER INDEX "ix_instantaneas_kpi_kpi_code" RENAME TO "ix_kpi_snapshots_kpi_code"')
    op.execute('ALTER INDEX "ix_instantaneas_kpi_company_id" RENAME TO "ix_kpi_snapshots_company_id"')
    op.execute('ALTER INDEX "ix_recuperaciones_password_user_id" RENAME TO "ix_password_resets_user_id"')
    op.execute('ALTER INDEX "ix_recuperaciones_password_token_hash" RENAME TO "ix_password_resets_token_hash"')
    op.execute('ALTER INDEX "ix_intentos_login_attempted_at" RENAME TO "ix_login_attempts_attempted_at"')
    op.execute('ALTER INDEX "ix_intentos_login_user_id" RENAME TO "ix_login_attempts_user_id"')
    op.execute('ALTER INDEX "ix_tokens_refresco_token_hash" RENAME TO "ix_refresh_tokens_token_hash"')
    op.execute('ALTER INDEX "ix_tokens_refresco_user_id" RENAME TO "ix_refresh_tokens_user_id"')
    op.execute('ALTER INDEX "ix_roles_permisos_role_id" RENAME TO "ix_role_permissions_role_id"')
    op.execute('ALTER INDEX "ix_roles_permisos_permission_id" RENAME TO "ix_role_permissions_permission_id"')
    op.execute('ALTER INDEX "ix_envios_company_id" RENAME TO "ix_shipments_company_id"')
    op.execute('ALTER INDEX "ix_envios_sale_id" RENAME TO "ix_shipments_sale_id"')
    op.execute('ALTER INDEX "ix_detalle_conteos_product_id" RENAME TO "ix_stock_count_details_product_id"')
    op.execute('ALTER INDEX "ix_detalle_conteos_stock_count_id" RENAME TO "ix_stock_count_details_stock_count_id"')
    op.execute('ALTER INDEX "ix_conteos_stock_company_id" RENAME TO "ix_stock_counts_company_id"')
    op.execute('ALTER INDEX "ix_conteos_stock_warehouse_id" RENAME TO "ix_stock_counts_warehouse_id"')
    op.execute('ALTER INDEX "ix_stock_almacenes_product_id" RENAME TO "ix_warehouse_stocks_product_id"')
    op.execute('ALTER INDEX "ix_stock_almacenes_warehouse_id" RENAME TO "ix_warehouse_stocks_warehouse_id"')
    op.execute('ALTER INDEX "ix_almacenes_company_id" RENAME TO "ix_warehouses_company_id"')
    op.execute('ALTER INDEX "ix_interacciones_clientes_company_id" RENAME TO "ix_customer_interactions_company_id"')
    op.execute('ALTER INDEX "ix_interacciones_clientes_customer_id" RENAME TO "ix_customer_interactions_customer_id"')
    op.execute('ALTER INDEX "ix_segmentos_clientes_company_id" RENAME TO "ix_customer_segments_company_id"')
    op.execute('ALTER INDEX "ix_productos_promociones_promotion_id" RENAME TO "ix_product_promotions_promotion_id"')
    op.execute('ALTER INDEX "ix_productos_promociones_product_id" RENAME TO "ix_product_promotions_product_id"')
    op.execute('ALTER INDEX "ix_promociones_company_id" RENAME TO "ix_promotions_company_id"')
    op.execute('ALTER INDEX "ix_detalle_listas_precios_product_id" RENAME TO "ix_price_list_items_product_id"')
    op.execute('ALTER INDEX "ix_detalle_listas_precios_price_list_id" RENAME TO "ix_price_list_items_price_list_id"')
    op.execute('ALTER INDEX "ix_listas_precios_company_id" RENAME TO "ix_price_lists_company_id"')
    op.execute('ALTER INDEX "ix_unidades_company_id" RENAME TO "ix_units_company_id"')
    op.execute('ALTER INDEX "ix_detalle_devoluciones_product_id" RENAME TO "ix_sales_return_details_product_id"')
    op.execute('ALTER INDEX "ix_detalle_devoluciones_return_id" RENAME TO "ix_sales_return_details_return_id"')
    op.execute('ALTER INDEX "ix_devoluciones_company_id" RENAME TO "ix_sales_returns_company_id"')
    op.execute('ALTER INDEX "ix_devoluciones_sale_id" RENAME TO "ix_sales_returns_sale_id"')
    op.execute('ALTER INDEX "ix_detalle_cotizaciones_quote_id" RENAME TO "ix_quote_details_quote_id"')
    op.execute('ALTER INDEX "ix_detalle_cotizaciones_product_id" RENAME TO "ix_quote_details_product_id"')
    op.execute('ALTER INDEX "ix_cotizaciones_company_id" RENAME TO "ix_quotes_company_id"')
    op.execute('ALTER INDEX "ix_cotizaciones_customer_id" RENAME TO "ix_quotes_customer_id"')
    op.execute('ALTER INDEX "ix_detalle_ordenes_compra_product_id" RENAME TO "ix_purchase_order_details_product_id"')
    op.execute('ALTER INDEX "ix_detalle_ordenes_compra_purchase_order_id" RENAME TO "ix_purchase_order_details_purchase_order_id"')
    op.execute('ALTER INDEX "ix_ordenes_compra_supplier_id" RENAME TO "ix_purchase_orders_supplier_id"')
    op.execute('ALTER INDEX "ix_ordenes_compra_company_id" RENAME TO "ix_purchase_orders_company_id"')
    op.execute('ALTER INDEX "ix_proveedores_company_id" RENAME TO "ix_suppliers_company_id"')
    op.execute('ALTER INDEX "ix_sucursales_company_id" RENAME TO "ix_branches_company_id"')
    op.execute('ALTER INDEX "ix_registros_auditoria_company_id" RENAME TO "ix_audit_logs_company_id"')
    op.execute('ALTER INDEX "ix_registros_auditoria_company_created" RENAME TO "ix_audit_logs_company_created"')
    op.execute('ALTER INDEX "ix_registros_auditoria_action" RENAME TO "ix_audit_logs_action"')
    op.execute('ALTER INDEX "ix_registros_auditoria_user_id" RENAME TO "ix_audit_logs_user_id"')
    op.execute('ALTER INDEX "ix_reportes_report_type" RENAME TO "ix_reports_report_type"')
    op.execute('ALTER INDEX "ix_reportes_company_id" RENAME TO "ix_reports_company_id"')
    op.execute('ALTER INDEX "ix_hallazgos_severity" RENAME TO "ix_insights_severity"')
    op.execute('ALTER INDEX "ix_hallazgos_rule_code" RENAME TO "ix_insights_rule_code"')
    op.execute('ALTER INDEX "ix_hallazgos_company_id" RENAME TO "ix_insights_company_id"')
    op.execute('ALTER INDEX "ix_hallazgos_analysis_id" RENAME TO "ix_insights_analysis_id"')
    op.execute('ALTER INDEX "ix_variables_aleatorias_company_id" RENAME TO "ix_random_variables_company_id"')
    op.execute('ALTER INDEX "ix_variables_aleatorias_analysis_id" RENAME TO "ix_random_variables_analysis_id"')
    op.execute('ALTER INDEX "ix_analisis_bayes_company_id" RENAME TO "ix_bayes_analyses_company_id"')
    op.execute('ALTER INDEX "ix_resultados_estadisticos_analysis_id" RENAME TO "ix_statistical_results_analysis_id"')
    op.execute('ALTER INDEX "ix_analisis_estadisticos_dataset_id" RENAME TO "ix_statistical_analyses_dataset_id"')
    op.execute('ALTER INDEX "ix_analisis_estadisticos_company_id" RENAME TO "ix_statistical_analyses_company_id"')
    op.execute('ALTER INDEX "ix_analisis_estadisticos_analysis_type" RENAME TO "ix_statistical_analyses_analysis_type"')
    op.execute('ALTER INDEX "ix_observaciones_dataset_id" RENAME TO "ix_observations_dataset_id"')
    op.execute('ALTER INDEX "ix_observaciones_data_gin" RENAME TO "ix_observations_data_gin"')
    op.execute('ALTER INDEX "ix_variables_conjunto_dataset_id" RENAME TO "ix_dataset_variables_dataset_id"')
    op.execute('ALTER INDEX "ix_conjuntos_datos_company_id" RENAME TO "ix_datasets_company_id"')
    op.execute('ALTER INDEX "ix_movimientos_inventario_product_id" RENAME TO "ix_inventory_movements_product_id"')
    op.execute('ALTER INDEX "ix_inventario_product_id" RENAME TO "ix_inventory_product_id"')
    op.execute('ALTER INDEX "ix_pagos_sale_id" RENAME TO "ix_payments_sale_id"')
    op.execute('ALTER INDEX "ix_detalle_ventas_sale_id" RENAME TO "ix_sale_details_sale_id"')
    op.execute('ALTER INDEX "ix_detalle_ventas_product_id" RENAME TO "ix_sale_details_product_id"')
    op.execute('ALTER INDEX "ix_ventas_seller_id" RENAME TO "ix_sales_seller_id"')
    op.execute('ALTER INDEX "ix_ventas_sale_number" RENAME TO "ix_sales_sale_number"')
    op.execute('ALTER INDEX "ix_ventas_sold_at" RENAME TO "ix_sales_sold_at"')
    op.execute('ALTER INDEX "ix_ventas_company_id" RENAME TO "ix_sales_company_id"')
    op.execute('ALTER INDEX "ix_ventas_customer_id" RENAME TO "ix_sales_customer_id"')
    op.execute('ALTER INDEX "ix_ventas_status" RENAME TO "ix_sales_status"')
    op.execute('ALTER INDEX "ix_productos_sku" RENAME TO "ix_products_sku"')
    op.execute('ALTER INDEX "ix_productos_category_id" RENAME TO "ix_products_category_id"')
    op.execute('ALTER INDEX "ix_productos_company_id" RENAME TO "ix_products_company_id"')
    op.execute('ALTER INDEX "ix_categorias_company_id" RENAME TO "ix_categories_company_id"')
    op.execute('ALTER INDEX "ix_clientes_document_number" RENAME TO "ix_customers_document_number"')
    op.execute('ALTER INDEX "ix_clientes_company_id" RENAME TO "ix_customers_company_id"')
    op.execute('ALTER INDEX "ix_empleados_company_id" RENAME TO "ix_employees_company_id"')
    op.execute('ALTER INDEX "ix_usuarios_company_id" RENAME TO "ix_users_company_id"')
    op.execute('ALTER INDEX "ix_usuarios_email" RENAME TO "ix_users_email"')

    op.rename_table('almacenes', 'warehouses')
    op.rename_table('stock_almacenes', 'warehouse_stocks')
    op.rename_table('usuarios', 'users')
    op.rename_table('unidades', 'units')
    op.rename_table('ajustes_sistema', 'system_settings')
    op.rename_table('proveedores', 'suppliers')
    op.rename_table('conteos_stock', 'stock_counts')
    op.rename_table('detalle_conteos', 'stock_count_details')
    op.rename_table('resultados_estadisticos', 'statistical_results')
    op.rename_table('analisis_estadisticos', 'statistical_analyses')
    op.rename_table('envios', 'shipments')
    op.rename_table('reportes_programados', 'scheduled_reports')
    op.rename_table('devoluciones', 'sales_returns')
    op.rename_table('detalle_devoluciones', 'sales_return_details')
    op.rename_table('ventas', 'sales')
    op.rename_table('detalle_ventas', 'sale_details')
    op.rename_table('roles_permisos', 'role_permissions')
    op.rename_table('reportes', 'reports')
    op.rename_table('tokens_refresco', 'refresh_tokens')
    op.rename_table('variables_aleatorias', 'random_variables')
    op.rename_table('cotizaciones', 'quotes')
    op.rename_table('detalle_cotizaciones', 'quote_details')
    op.rename_table('ordenes_compra', 'purchase_orders')
    op.rename_table('detalle_ordenes_compra', 'purchase_order_details')
    op.rename_table('promociones', 'promotions')
    op.rename_table('productos', 'products')
    op.rename_table('productos_promociones', 'product_promotions')
    op.rename_table('listas_precios', 'price_lists')
    op.rename_table('detalle_listas_precios', 'price_list_items')
    op.rename_table('permisos', 'permissions')
    op.rename_table('pagos', 'payments')
    op.rename_table('recuperaciones_password', 'password_resets')
    op.rename_table('observaciones', 'observations')
    op.rename_table('notificaciones', 'notifications')
    op.rename_table('intentos_login', 'login_attempts')
    op.rename_table('instantaneas_kpi', 'kpi_snapshots')
    op.rename_table('movimientos_inventario', 'inventory_movements')
    op.rename_table('inventario', 'inventory')
    op.rename_table('hallazgos', 'insights')
    op.rename_table('empleados', 'employees')
    op.rename_table('conjuntos_datos', 'datasets')
    op.rename_table('variables_conjunto', 'dataset_variables')
    op.rename_table('exportaciones_datos', 'data_exports')
    op.rename_table('clientes', 'customers')
    op.rename_table('segmentos_clientes', 'customer_segments')
    op.rename_table('interacciones_clientes', 'customer_interactions')
    op.rename_table('empresas', 'companies')
    op.rename_table('categorias', 'categories')
    op.rename_table('sucursales', 'branches')
    op.rename_table('analisis_bayes', 'bayes_analyses')
    op.rename_table('reglas_automatizacion', 'automation_rules')
    op.rename_table('registros_auditoria', 'audit_logs')
    op.rename_table('eventos_app', 'app_events')
